rement.parse('azure-mgmt-network<=25.2.0')).
Using default local authentication
Traceback (most recent call last):
  File ".\pipeline_runner.py", line 81, in <module>
    output_path_on_datastore=custom_output_path.path,
AttributeError: 'DataPath' object has no attribute 'path'
