File /anaconda/envs/azureml_py38/lib/python3.10/site-packages/pandas/_libs/interval.pyx:1, in init pandas._libs.interval()

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

pip install --force-reinstall --no-cache-dir numpy pandas
