MATCH ROUND 17: Alternates
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.11137199401855469 seconds
Traceback (most recent call last):
  File "cross_hound/matcher.py", line 1474, in <module>
    main(input_dir=args.get('input_dir'),
  File "cross_hound/matcher.py", line 1299, in main
    matched, unmatched = full_matching_routine(data_version, db_style, device,
  File "cross_hound/matcher.py", line 1251, in full_matching_routine
    current_full_matches, erp_to_match, tru_to_match = check_for_alternates(erp_to_match,
  File "cross_hound/matcher.py", line 646, in check_for_alternates
    collected = pd.concat(list_res, ignore_index=True, axis=0)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 372, in concat
    op = _Concatenator(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 429, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
